name: 01 - Main CI / CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:


# Otorgamos los permisos globalmente
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  secret-scan:
    name: Secret Scan
    uses: ./.github/workflows/secret-scan.yml
    secrets: inherit

  build:
    needs: secret-scan
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  #Análisis de dependencias
  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit

  #Análisis de código Estático
  sast:
    needs: build
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  #Análisis y Uso de Licencias.
  license-compliance:
    needs: build
    name: License Compliance
    uses: ./.github/workflows/license-compliance.yml
    secrets: inherit

  #Creación de Docker
  docker:
    needs: [sast, sca] # Wait for security checks before building image? Or just parallel? security-complete built image later. 
                       # Usually good to fail fast if SAST/SCA fail.
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit
  
  #Scaneo de vulnerabilidades en la imagen de Docker
  container-image-scan:
    needs: docker
    name: Container Image Scan
    uses: ./.github/workflows/container-image-scan.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}


  #Análisis de código Dinámico
  dast:
    needs: [container-image-scan, docker]
    name: DAST Scan
    uses: ./.github/workflows/dast.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}

  
  
